language: python
# Define language

os:
  - linux
  #- osx
# Define operating system's to test

after_success:
  - coverage combine .coverage_*
  - bash <(curl -s https://codecov.io/bash)
  # Combines and sends coverage reports to codecov
# Define actions after successful build

python:
  #- "3.4"
  #- "3.5"
  - "3.6"      # current default Python on Travis CI
  #- "3.7"
  #- "3.8"
  #- "3.8-dev"  # 3.8 development branch
  #- "nightly"  # nightly build
# Specify versions of language to test

install:
  - pip install coverage
  # Installing coverage for coverage reports for codecov
# Install dependencies

# command to run tests
script:
  - COVERAGE_FILE=.coverage_v coverage run referee.py --version
  - COVERAGE_FILE=.coverage_pileup coverage run referee.py -gl tests/data/test.pileup --pileup -ref tests/data/test.fa -d tests/out/ -prefix test-out --fastq --fasta --bed --correct --raw -p 8 
# Tests to run