#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=24,walltime=36:00:00,vmem=200GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N run-angsd-om
#PBS -j oe

cd /N/dc2/scratch/grthomas/qtip/owl-monkey/
bamfile="/N/dcwan/projects/hahnlab-phi/owl-monkey/swapRef/owl-monkey-120ref-sorted.bam"
reffile="/N/dcwan/projects/hahnlab-phi/owl-monkey/ref-genome/genbank/GCA_000952055.2_Anan_2.0_genomic.fna"
time -p angsd -P 24 -GL 2 -i $bamfile -ref $reffile -minQ 0 -doGlf 4 -out owl-monkey-angsd
