#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=24,walltime=24:00:00,vmem=100GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N run-angsd-om
#PBS -j oe

cd /N/u/grthomas/Carbonate/bin/referee/
python helper-scripts/run_angsd.py -p 23 -s /N/dc2/scratch/grthomas/qtip/owl-monkey/scaffold-list.txt -r /N/dcwan/projects/hahnlab-phi/owl-monkey/ref-genome/genbank/GCA_000952055.2_Anan_2.0_genomic.fna -b /N/dc2/scratch/grthomas/qtip/owl-monkey/split-bam-out/ -o /N/dc2/scratch/grthomas/qtip/owl-monkey/angsd-out/