#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=24,walltime=36:00:00,vmem=100GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N run-angsd-bab
#PBS -j oe

cd /N/dc2/scratch/grthomas/qtip/baboon/
bamfile="/N/dc2/scratch/grthomas/qtip/baboon/mapped/baboon-reads-sorted.bam"
reffile="/N/dc2/scratch/grthomas/qtip/baboon/assembly/GCA_000264685.2_Panu_3.0_genomic.fna"
time -p angsd -P 24 -GL 2 -i $bamfile -ref $reffile -minQ 0 -doGlf 4 -out baboon-angsd
