#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=24,walltime=36:00:00,vmem=100GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N baboon-angsd
#PBS -j oe

refdir="/N/u/grthomas/Carbonate/bin/referee"
babdir="/N/dc2/scratch/grthomas/qtip/baboon"
bamfile="/N/dc2/scratch/grthomas/qtip/baboon/mapped/baboon-reads-sorted.bam"
reffile="/N/dc2/scratch/grthomas/qtip/baboon/GCA_000264685.1_Panu_2.0_genomic.fna"
cd $babdir

time -p angsd -P 24 -GL 2 -i $bamfile -ref $reffile -minQ 0 -doGlf 4 -out bab-angsd
# ANGSD command

#module load samtools/1.9
#samtools mpileup -d 999999999 -f $babdir/assembly/GCA_000264685.2_Panu_3.0_genomic.fna -Q 0 -B -s -o bab.pileup $babdir/mapped/baboon-reads-sorted.bam
# pileup command with mapping quality (-s) and no baq recalculation (-B)

#cd $refdir