#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=22,walltime=72:00:00,vmem=100GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N baboon-referee
#PBS -j oe

refdir="/N/u/grthomas/Carbonate/bin/referee"
babdir="/N/dc2/scratch/grthomas/qtip/baboon"
bamfile="/N/dc2/scratch/grthomas/qtip/baboon/mapped/baboon-chromes-sorted.bam"
reffile="/N/dc2/scratch/grthomas/qtip/baboon/assembly/baboon-chromes.fa"
cd $babdir

#time -p angsd -P 24 -GL 2 -i $bamfile -ref $reffile -minQ 0 -doGlf 4 -out bab-angsd
# ANGSD command

#module load samtools/1.9
#samtools mpileup -d 999999999 -f $reffile -Q 0 -B -s -o bab.pileup $bamfile
# pileup command with mapping quality (-s) and no baq recalculation (-B)

#angsdin="/N/dc2/scratch/grthomas/qtip/baboon/bab-angsd.glf.gz"
#pilemqin="/N/dc2/scratch/grthomas/qtip/baboon/bab.pileup"
pilemqin="/N/dc2/scratch/grthomas/qtip/baboon/bab-pileup.txt"
angsdin="/N/dc2/scratch/grthomas/qtip/baboon/bab-angsd.txt"

outdir="/N/dc2/scratch/grthomas/qtip/baboon/time-tests-3"
refpath="/N/u/grthomas/Carbonate/bin/referee/referee.py"

ps=(22 12 6 1)

for i in ${ps[*]}; do 
    time -p python $refpath -gl $angsdin -ref $reffile --fastq --correct --bed --raw -o $outdir/angsd-$i -p $i
    time -p python $refpath -gl $pilemqin -ref $reffile --fastq --correct --pileup --bed --raw -o $outdir/pileup-$i -p $i
    time -p python $refpath -gl $pilemqin -ref $reffile --fastq --correct --pileup --mapq --bed --raw -o $outdir/pileup-mq-$i -p $i
done