#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=12:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N jsinuosa-index
#PBS -j oe

module load bwa/0.7.12
module load samtools/1.5
ref="/N/dc2/scratch/grthomas/qtip/jsinuosa/assembly/trinity_out_dir/Trinity.fasta"
srr="SRR5380902"
fq1_id="SRR5380902_1"
fq1_path="/N/dc2/scratch/grthomas/qtip/jsinuosa/reads/$fq1_id.fastq"
fq2_id="SRR5380902_2"
fq2_path="/N/dc2/scratch/grthomas/qtip/jsinuosa/reads/$fq2_id.fastq"
outdir="/N/dc2/scratch/grthomas/qtip/jsinuosa/mapped/"
# Setting paths

samtools faidx $ref
# Index reference

#sai1_out="$outdir$fq1_id.sai"
#bwa aln $ref $fq1_path > $sai1_out
# SAI1

#sai2_out="$outdir$fq2_id.sai"
#bwa aln $ref $fq2_path > $sai2_out
# SAI2

#sam_out="$outdir$srr.sam"
#bwa sampe $ref $sai1_out $sai2_out $fq1_path $fq2_path > $sam_out
# SAM

#bam_out="$outdir$srr.bam"
#samtools view -bS $sam_out > $bam_out
# BAM

# MAY ALSO HAVE TO SORT AND INDEX.