#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=4:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N jsin-comp-scores
#PBS -j oe

module load r/3.4.4
jsindir="/N/dc2/scratch/grthomas/qtip/jsinuosa"
Rscript /N/u/grthomas/Carbonate/bin/referee/helper-scripts/comp_scores.r $jsindir/jsin-referee-out-1proc-glcalcs.txt $jsindir/jsin-referee-out-1proc-glcalcs-nobaq.txt $jsindir/jsin-plots jsin-glcalcs-vs-glcalcs-nobaq