#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=5,walltime=4:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N jsin-referee-tests
#PBS -j oe

cd /N/u/grthomas/Carbonate/bin/referee/
jsindir="/N/dc2/scratch/grthomas/qtip/jsinuosa"
#time -p python referee.py -gl $jsindir/jsinuosa-angsd.glf.gz  -ref $jsindir/assembly/Trinity.fasta --stats --fastq --correct -o $jsindir/jsin-referee-out-1proc
# ANGSD input

time -p python referee.py -gl $jsindir/jsinuosa-mq.pileup  -ref $jsindir/assembly/Trinity.fasta --pileup --stats --fastq --correct -o $jsindir/jsin-referee-out-4proc-glcalcs-mq -p 4
# pileup input with mq

#time -p python referee.py -gl $jsindir/jsinuosa.pileup  -ref $jsindir/assembly/Trinity.fasta --pileup --stats --fastq --correct -o $jsindir/jsin-referee-out-1proc-glcalcs -p 4
# pileup input no mq