#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=4:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N jsin-comp-scores
#PBS -j oe

module load r/3.4.4
jsindir="/N/dc2/scratch/grthomas/qtip/jsinuosa"
Rscript /N/u/grthomas/Carbonate/bin/referee/helper-scripts/comp_scores.r $jsindir/jsin-referee-out-angsd-s1.txt $jsindir/jsin-referee-out-angsd-s2.txt $jsindir/jsin-plots-3 jsin-angsds1-vs-angsds2
Rscript /N/u/grthomas/Carbonate/bin/referee/helper-scripts/comp_scores.r $jsindir/jsin-referee-out-pileup-s1.txt $jsindir/jsin-referee-out-pileup-s2.txt $jsindir/jsin-plots-3 jsin-pileups1-vs-pileups2

#Rscript /N/u/grthomas/Carbonate/bin/referee/helper-scripts/comp_scores.r $jsindir/jsin-referee-out-angsd-s1.txt $jsindir/jsin-referee-out-pileup-s1.txt $jsindir/jsin-plots-3 jsin-angsds1-vs-pileups1
