#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=8,walltime=12:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N jsin-referee-tests
#PBS -j oe

cd /N/u/grthomas/Carbonate/bin/referee/
jsindir="/N/dc2/scratch/grthomas/qtip/jsinuosa"
time -p python referee.py -gl $jsindir/jsinuosa-angsd.glf.gz -ref $jsindir/assembly/Trinity.fasta --fastq --correct -o $jsindir/jsin-referee-out-8proc -p 8
# ANGSD input

time -p python referee.py -gl $jsindir/jsinuosa-mq.pileup -ref $jsindir/assembly/Trinity.fasta --pileup --fastq --correct -o $jsindir/jsin-referee-out-8proc-glcalcs-mq -p 8
# pileup input with mq

time -p python referee.py -gl $jsindir/jsinuosa.pileup -ref $jsindir/assembly/Trinity.fasta --pileup --fastq --correct -o $jsindir/jsin-referee-out-8proc-glcalcs -p 8
# pileup input no mq