#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=2,walltime=4:00:00,vmem=48GB
#PBS -M grthomas@indiana.edu
#PBS -m abe
#PBS -N referee-tests
#PBS -j oe

#module load biopython/1.70
# Biopython needed for -f 3
cd /N/u/grthomas/Carbonate/bin/referee/
time -p python referee.py -gl /N/dc2/scratch/grthomas/qtip/angsd-doglf4/angsdput.glf.gz -ref data/rpgc_assembly.fasta --stats --fastq --correct -o ref-test-1-1 -f 1

